import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

export interface AgentHostGeneratedArtifact {
  artifactRef: string;
  validatorRef: string;
  artifact: Record<string, unknown>;
  validatorArtifact: Record<string, unknown>;
  evidenceRefs: string[];
  title: string;
}

export function isOnePagePresentationArtifactRequest(text: string): boolean {
  const normalized = text.replace(/\s+/g, ' ').trim();
  if (!normalized) return false;
  const asksPresentation = /(?:pptx?|power\s*point|presentation|slide\s*deck|slides?|deck|演示文稿|幻灯片|幻灯|PPT)/i.test(normalized);
  const asksCreation = /(?:create|make|generate|draft|build|做|生成|制作|创建|写|出|产出)/i.test(normalized);
  const asksSinglePage = /(?:one|single|1|一)\s*(?:page|slide|页|张|个)?/i.test(normalized)
    || /(?:一页|一张|单页|单张|one-page|single-slide)/i.test(normalized);
  const asksDesktopGui = /(?:open|click|mouse|keyboard|desktop|app|powerpoint\s+app|打开|点击|鼠标|键盘|桌面|应用|窗口)/i.test(normalized);
  return asksPresentation && asksCreation && (asksSinglePage || !/\b(?:multi|multiple|several|多页|多张)\b/i.test(normalized)) && !asksDesktopGui;
}

export async function generateOnePagePresentationArtifact(input: {
  workspacePath: string;
  commandId: string;
  attemptId: string;
  prompt: string;
}): Promise<AgentHostGeneratedArtifact> {
  const runId = safeRunId(`${input.commandId}-${input.attemptId}`);
  const runDirRef = `.sciforge/vision-runs/${runId}`;
  const runDir = join(input.workspacePath, runDirRef);
  await mkdir(runDir, { recursive: true });

  const title = presentationTitle(input.prompt);
  const subtitle = presentationSubtitle(input.prompt);
  const artifactRef = `${runDirRef}/one-page-presentation.pptx`;
  const validatorRef = `${artifactRef}.validation.json`;
  const pptxBytes = buildOneSlidePptx({
    title,
    subtitle,
    footer: 'Generated by Codex Agent Host artifact path.',
  });
  await writeFile(join(input.workspacePath, artifactRef), pptxBytes);

  const artifactHash = sha256(pptxBytes);
  const validation = await validateGeneratedPresentationArtifact({
    workspacePath: input.workspacePath,
    artifactRef,
    validatorRef,
    expectedSha256: artifactHash,
  });
  await writeFile(join(input.workspacePath, validatorRef), JSON.stringify(validation, null, 2), 'utf8');

  const artifact = {
    id: artifactRef,
    type: 'presentation',
    path: artifactRef,
    dataRef: artifactRef,
    metadata: {
      source: 'codex-agent-host-artifact-generator',
      format: 'pptx',
      finalArtifactRef: artifactRef,
      artifactValidationRef: validatorRef,
      artifactRefs: [artifactRef, validatorRef],
      sha256: artifactHash,
    },
  };
  const validatorArtifact = {
    id: validatorRef,
    type: 'artifact-validation',
    path: validatorRef,
    dataRef: validatorRef,
    metadata: {
      source: 'codex-agent-host-artifact-generator',
      validator: validation.validator,
      finalArtifactRef: artifactRef,
      artifactValidationRef: validatorRef,
      status: validation.status,
    },
  };
  return {
    artifactRef,
    validatorRef,
    artifact,
    validatorArtifact,
    evidenceRefs: [artifactRef, validatorRef],
    title,
  };
}

async function validateGeneratedPresentationArtifact(input: {
  workspacePath: string;
  artifactRef: string;
  validatorRef: string;
  expectedSha256: string;
}) {
  const bytes = await readFile(join(input.workspacePath, input.artifactRef));
  const entries = listStoredZipEntries(bytes);
  const requiredEntries = [
    '[Content_Types].xml',
    '_rels/.rels',
    'ppt/presentation.xml',
    'ppt/_rels/presentation.xml.rels',
    'ppt/slides/slide1.xml',
  ];
  const missingEntries = requiredEntries.filter((entry) => !entries.includes(entry));
  const sha = sha256(bytes);
  const passed = bytes.subarray(0, 4).equals(Buffer.from([0x50, 0x4b, 0x03, 0x04]))
    && sha === input.expectedSha256
    && missingEntries.length === 0;
  return {
    schemaVersion: 'sciforge.agent-host.presentation-artifact-validation.v1',
    status: passed ? 'passed' : 'failed',
    validator: 'sciforge-agent-host-one-page-pptx-validator',
    productAcceptanceEvidence: true,
    finalArtifactRef: input.artifactRef,
    artifactValidationRef: input.validatorRef,
    format: 'pptx',
    slideCount: entries.filter((entry) => /^ppt\/slides\/slide\d+\.xml$/i.test(entry)).length,
    sha256: sha,
    contentRefs: [input.artifactRef],
    sourceRefs: [input.artifactRef],
    entries,
    missingEntries,
  };
}

function buildOneSlidePptx(input: { title: string; subtitle: string; footer: string }): Buffer {
  const files: Array<[string, string]> = [
    ['[Content_Types].xml', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/>
  <Override PartName="/ppt/slides/slide1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>
</Types>`],
    ['_rels/.rels', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/>
</Relationships>`],
    ['ppt/presentation.xml', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:presentation xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <p:sldIdLst><p:sldId id="256" r:id="rId1"/></p:sldIdLst>
  <p:sldSz cx="12192000" cy="6858000" type="screen16x9"/>
  <p:notesSz cx="6858000" cy="9144000"/>
</p:presentation>`],
    ['ppt/_rels/presentation.xml.rels', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide1.xml"/>
</Relationships>`],
    ['ppt/slides/slide1.xml', slideXml(input)],
  ];
  return storedZip(files.map(([name, text]) => [name, Buffer.from(text, 'utf8')]));
}

function slideXml(input: { title: string; subtitle: string; footer: string }) {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">
  <p:cSld>
    <p:spTree>
      <p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>
      <p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>
      ${textBoxXml(2, 'Title', input.title, 914400, 685800, 10363200, 1000000, 3600)}
      ${textBoxXml(3, 'Subtitle', input.subtitle, 914400, 1828800, 10363200, 2000000, 2200)}
      ${textBoxXml(4, 'Footer', input.footer, 914400, 5486400, 10363200, 500000, 1200)}
    </p:spTree>
  </p:cSld>
  <p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr>
</p:sld>`;
}

function textBoxXml(id: number, name: string, text: string, x: number, y: number, cx: number, cy: number, fontSize: number) {
  return `<p:sp>
  <p:nvSpPr><p:cNvPr id="${id}" name="${escapeXml(name)}"/><p:cNvSpPr txBox="1"/><p:nvPr/></p:nvSpPr>
  <p:spPr><a:xfrm><a:off x="${x}" y="${y}"/><a:ext cx="${cx}" cy="${cy}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:noFill/></p:spPr>
  <p:txBody><a:bodyPr wrap="square"/><a:lstStyle/><a:p><a:r><a:rPr lang="en-US" sz="${fontSize}"/><a:t>${escapeXml(text)}</a:t></a:r></a:p></p:txBody>
</p:sp>`;
}

function storedZip(files: Array<[string, Buffer]>): Buffer {
  const locals: Buffer[] = [];
  const centrals: Buffer[] = [];
  let offset = 0;
  for (const [name, data] of files) {
    const nameBytes = Buffer.from(name, 'utf8');
    const crc = crc32(data);
    const local = Buffer.alloc(30 + nameBytes.length);
    local.writeUInt32LE(0x04034b50, 0);
    local.writeUInt16LE(20, 4);
    local.writeUInt16LE(0, 6);
    local.writeUInt16LE(0, 8);
    local.writeUInt16LE(0, 10);
    local.writeUInt16LE(0, 12);
    local.writeUInt32LE(crc, 14);
    local.writeUInt32LE(data.length, 18);
    local.writeUInt32LE(data.length, 22);
    local.writeUInt16LE(nameBytes.length, 26);
    local.writeUInt16LE(0, 28);
    nameBytes.copy(local, 30);
    locals.push(local, data);

    const central = Buffer.alloc(46 + nameBytes.length);
    central.writeUInt32LE(0x02014b50, 0);
    central.writeUInt16LE(20, 4);
    central.writeUInt16LE(20, 6);
    central.writeUInt16LE(0, 8);
    central.writeUInt16LE(0, 10);
    central.writeUInt16LE(0, 12);
    central.writeUInt16LE(0, 14);
    central.writeUInt32LE(crc, 16);
    central.writeUInt32LE(data.length, 20);
    central.writeUInt32LE(data.length, 24);
    central.writeUInt16LE(nameBytes.length, 28);
    central.writeUInt16LE(0, 30);
    central.writeUInt16LE(0, 32);
    central.writeUInt16LE(0, 34);
    central.writeUInt16LE(0, 36);
    central.writeUInt32LE(0, 38);
    central.writeUInt32LE(offset, 42);
    nameBytes.copy(central, 46);
    centrals.push(central);
    offset += local.length + data.length;
  }
  const centralDirectory = Buffer.concat(centrals);
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(0, 4);
  end.writeUInt16LE(0, 6);
  end.writeUInt16LE(files.length, 8);
  end.writeUInt16LE(files.length, 10);
  end.writeUInt32LE(centralDirectory.length, 12);
  end.writeUInt32LE(offset, 16);
  end.writeUInt16LE(0, 20);
  return Buffer.concat([...locals, centralDirectory, end]);
}

function listStoredZipEntries(bytes: Buffer): string[] {
  const entries: string[] = [];
  for (let index = 0; index < bytes.length - 4;) {
    if (bytes.readUInt32LE(index) !== 0x04034b50) break;
    const compressedSize = bytes.readUInt32LE(index + 18);
    const nameLength = bytes.readUInt16LE(index + 26);
    const extraLength = bytes.readUInt16LE(index + 28);
    entries.push(bytes.subarray(index + 30, index + 30 + nameLength).toString('utf8'));
    index += 30 + nameLength + extraLength + compressedSize;
  }
  return entries;
}

function presentationTitle(prompt: string) {
  const cleaned = prompt
    .replace(/(?:请|帮我|给我|做|生成|制作|创建|create|make|generate|draft|build|一页|一张|single|one|pptx?|power\s*point|presentation|slides?|deck|演示文稿|幻灯片|幻灯)/gi, ' ')
    .replace(/[，。,.!！？?]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  return limitText(cleaned || 'One-page presentation', 80);
}

function presentationSubtitle(prompt: string) {
  return limitText(`Request: ${prompt.replace(/\s+/g, ' ').trim()}`, 180);
}

function safeRunId(value: string) {
  const slug = value.toLowerCase().replace(/[^a-z0-9._-]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 72);
  return slug || `artifact-${sha256(Buffer.from(value)).slice(0, 12)}`;
}

function limitText(value: string, max: number) {
  return value.length > max ? `${value.slice(0, Math.max(0, max - 3))}...` : value;
}

function escapeXml(value: string) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function sha256(value: Buffer) {
  return createHash('sha256').update(value).digest('hex');
}

function crc32(data: Buffer) {
  let crc = 0xffffffff;
  for (const byte of data) {
    crc ^= byte;
    for (let bit = 0; bit < 8; bit += 1) {
      crc = (crc >>> 1) ^ (0xedb88320 & -(crc & 1));
    }
  }
  return (crc ^ 0xffffffff) >>> 0;
}
