import { sanitizePublicEvent } from '@sciforge-ui/runtime-contract/public-event-sanitizer';
import { createCodexAppServerRuntimeAdapter } from './codex-runtime-adapter.js';
import { codexRuntimeBridgeRequested } from './codex-runtime-server.js';
import type { GatewayRequest, ToolPayload, WorkspaceRuntimeCallbacks, WorkspaceRuntimeEvent } from '../runtime-types.js';
import { emitWorkspaceRuntimeEvent } from '../workspace-runtime-events.js';

export async function tryRunCodexRuntimeGateway(
  request: GatewayRequest,
  callbacks: WorkspaceRuntimeCallbacks = {},
): Promise<ToolPayload | undefined> {
  if (!codexRuntimeBridgeRequested(request as unknown as Record<string, unknown>)) return undefined;
  const adapter = createCodexAppServerRuntimeAdapter();
  const turn = await adapter.startTurn({
    commandText: request.prompt,
    workspacePath: request.workspacePath ?? '',
    codexSessionId: codexSessionIdFromRequest(request),
    allowOpenAiRuntime: allowOpenAiRuntime(request),
    abortSignal: callbacks.signal,
  });
  const chunks: string[] = [];
  const logs: Array<Record<string, unknown>> = [];
  const publicEvidenceRefs: string[] = [];
  for await (const event of turn.events) {
    const eventRecord = event as unknown as Record<string, unknown>;
    logs.push(eventRecord);
    publicEvidenceRefs.push(...safePublicRefsFromValue(eventRecord));
    const publicEvent = sanitizePublicEvent({
      type: `codex-runtime-${event.type}`,
      status: event.status ?? event.type,
      source: 'codex-app-server',
      message: event.message,
      text: event.text,
      evidenceRefs: uniqueStrings([
        ...stringList(event.evidenceRefs),
        ...safePublicRefsFromValue(eventRecord),
      ]),
      output: eventRecord.output,
      error: eventRecord.error,
    }) as WorkspaceRuntimeEvent;
    emitWorkspaceRuntimeEvent(callbacks, publicEvent);
    if (event.type === 'message' || event.type === 'message_delta') {
      if (event.text) chunks.push(event.text);
    }
    if (event.type === 'failed') {
      throw new Error(event.message ?? 'Runtime Codex failed.');
    }
  }
  const message = chunks.join('').trim();
  if (!message) {
    return runtimeCodexMissingFinalAnswerPayload(turn.turnId, logs, uniqueStrings(publicEvidenceRefs));
  }
  return sanitizePublicEvent({
    message,
    claimType: 'runtime-codex-result',
    evidenceLevel: 'runtime-normalized-events',
    reasoningTrace: 'Generated by Runtime Codex through Codex app-server rich-client events.',
    claims: [],
    uiManifest: [],
    executionUnits: [{
      id: `EU-${turn.turnId}`,
      status: 'done',
      title: 'Runtime Codex turn',
      provider: logs[0]?.provider,
      model: logs[0]?.model,
      profile: logs[0]?.profile,
      workspace: logs[0]?.workspace,
      commandId: turn.turnId,
    }],
    artifacts: [],
    logs,
  }) as ToolPayload;
}

function runtimeCodexMissingFinalAnswerPayload(
  turnId: string,
  logs: Array<Record<string, unknown>>,
  publicEvidenceRefs: string[] = [],
): ToolPayload {
  const first = logs[0] ?? {};
  const last = logs[logs.length - 1] ?? first;
  const evidenceRefs = uniqueStrings([
    ...stringList(last.evidenceRefs),
    ...publicEvidenceRefs,
  ]);
  return sanitizePublicEvent({
    message: 'Runtime Codex completed without a safe final assistant answer; final-answer-required.',
    claimType: 'runtime-codex-blocked',
    evidenceLevel: 'runtime-normalized-events',
    reasoningTrace: 'Runtime Codex emitted terminal/progress events without a Host final answer message; SciForge failed closed.',
    claims: [{
      type: 'runtime-codex-final-answer-required',
      status: 'blocked',
      boundary: 'final-answer-required',
      evidenceRefs,
    }],
    uiManifest: [],
    executionUnits: [{
      id: `EU-${turnId}`,
      status: 'blocked',
      title: 'Runtime Codex turn',
      provider: first.provider,
      model: first.model,
      profile: first.profile,
      workspace: first.workspace,
      commandId: turnId,
      failureReason: 'final-answer-required',
      boundary: 'final-answer-required',
    }],
    artifacts: [],
    displayIntent: {
      status: 'blocked',
      boundary: 'final-answer-required',
    },
    logs,
  }) as ToolPayload;
}

function stringList(value: unknown): string[] {
  return Array.isArray(value) ? value.filter((entry): entry is string => typeof entry === 'string' && entry.trim().length > 0) : [];
}

function safePublicRefsFromValue(value: unknown): string[] {
  const refs: string[] = [];
  collectRefsFromValue(value, undefined, refs);
  const sanitized = sanitizePublicEvent({ evidenceRefs: refs }) as Record<string, unknown>;
  return stringList(sanitized.evidenceRefs);
}

function collectRefsFromValue(value: unknown, key: string | undefined, refs: string[]) {
  if (typeof value === 'string') {
    if (key && /(?:^|[-_])refs?$/i.test(key.replace(/([a-z0-9])([A-Z])/g, '$1-$2'))) refs.push(value);
    return;
  }
  if (!value || typeof value !== 'object') return;
  if (Array.isArray(value)) {
    for (const item of value) collectRefsFromValue(item, key, refs);
    return;
  }
  for (const [childKey, childValue] of Object.entries(value as Record<string, unknown>)) {
    collectRefsFromValue(childValue, childKey, refs);
  }
}

function uniqueStrings(values: string[]): string[] {
  return [...new Set(values.filter((value) => value.trim().length > 0))];
}

function allowOpenAiRuntime(request: GatewayRequest): boolean {
  const uiState = request.uiState && typeof request.uiState === 'object' ? request.uiState : {};
  void uiState;
  return false;
}

function codexSessionIdFromRequest(request: GatewayRequest): string | undefined {
  const uiState = request.uiState && typeof request.uiState === 'object' ? request.uiState as Record<string, unknown> : {};
  const value = uiState.codexSessionId ?? uiState.nativeSessionId;
  return typeof value === 'string' && value.trim() ? value.trim() : undefined;
}
