import { createCodexAppServerRuntimeAdapter } from './codex-runtime-adapter.js';
import { codexRuntimeBridgeRequested } from './codex-runtime-server.js';
import type { GatewayRequest, ToolPayload, WorkspaceRuntimeCallbacks } from '../runtime-types.js';
import { emitWorkspaceRuntimeEvent } from '../workspace-runtime-events.js';

export async function tryRunCodexRuntimeGateway(
  request: GatewayRequest,
  callbacks: WorkspaceRuntimeCallbacks = {},
): Promise<ToolPayload | undefined> {
  if (!codexRuntimeBridgeRequested(request as unknown as Record<string, unknown>)) return undefined;
  const adapter = createCodexAppServerRuntimeAdapter();
  const turn = await adapter.startTurn({
    commandText: request.prompt,
    workspacePath: request.workspacePath ?? '',
    codexSessionId: codexSessionIdFromRequest(request),
    allowOpenAiRuntime: allowOpenAiRuntime(request),
    abortSignal: callbacks.signal,
  });
  const chunks: string[] = [];
  const logs: Array<Record<string, unknown>> = [];
  for await (const event of turn.events) {
    logs.push(event as unknown as Record<string, unknown>);
    emitWorkspaceRuntimeEvent(callbacks, {
      type: `codex-runtime-${event.type}`,
      status: event.status ?? event.type,
      source: 'codex-app-server',
      message: event.message,
      text: event.text,
      raw: event,
    });
    if (event.type === 'message' || event.type === 'message_delta') {
      if (event.text) chunks.push(event.text);
    }
    if (event.type === 'failed') {
      throw new Error(event.message ?? 'Runtime Codex failed.');
    }
  }
  const message = chunks.join('').trim() || 'Runtime Codex completed without a text response.';
  return {
    message,
    claimType: 'runtime-codex-result',
    evidenceLevel: 'runtime-normalized-events',
    reasoningTrace: 'Generated by Runtime Codex through Codex app-server rich-client events.',
    claims: [],
    uiManifest: [],
    executionUnits: [{
      id: `EU-${turn.turnId}`,
      status: 'done',
      title: 'Runtime Codex turn',
      provider: logs[0]?.provider,
      model: logs[0]?.model,
      profile: logs[0]?.profile,
      workspace: logs[0]?.workspace,
      commandId: turn.turnId,
    }],
    artifacts: [],
    logs,
  };
}

function allowOpenAiRuntime(request: GatewayRequest): boolean {
  const uiState = request.uiState && typeof request.uiState === 'object' ? request.uiState : {};
  return (uiState as Record<string, unknown>).allowOpenAiRuntime === true;
}

function codexSessionIdFromRequest(request: GatewayRequest): string | undefined {
  const uiState = request.uiState && typeof request.uiState === 'object' ? request.uiState as Record<string, unknown> : {};
  const value = uiState.codexSessionId ?? uiState.nativeSessionId;
  return typeof value === 'string' && value.trim() ? value.trim() : undefined;
}
