import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

const sidebarSource = readFileSync(new URL('./AnnotationSidebar.tsx', import.meta.url), 'utf8');
const sidebarCss = readFileSync(new URL('../styles/app-feedback.css', import.meta.url), 'utf8');

test('annotation sidebar renders intent-first references, action ladder, and save controls', () => {
  assert.match(sidebarSource, /aria-label="全局注释侧栏"/);
  assert.match(sidebarSource, /feedback flow/);
  assert.match(sidebarSource, /先说清楚，再选择下一步/);
  assert.match(sidebarSource, /SciForgeReferenceChips/);
  assert.match(sidebarSource, /ChatComposer/);
  assert.match(sidebarSource, /问题和关系/);
  assert.match(sidebarSource, /同一条反馈路径/);
  assert.match(sidebarSource, /showReferencePicker=\{false\}/);
  assert.match(sidebarSource, /showFileUpload=\{false\}/);
  assert.match(sidebarSource, /showCollapseButton=\{false\}/);
  assert.doesNotMatch(sidebarSource, /<textarea/);
  assert.match(sidebarSource, /保存反馈/);
  assert.match(sidebarSource, /预览修改/);
  assert.match(sidebarSource, /应用小改动/);
  assert.match(sidebarSource, /复杂改动进收件箱/);
  assert.match(sidebarSource, /assessAnnotationQuickAction/);
  assert.match(sidebarSource, /RunningWorkProcess/);
  assert.match(sidebarSource, /streamEvents/);
  assert.match(sidebarSource, /referenceComposerMarker/);
  assert.match(sidebarSource, /onReferenceFocus/);
  assert.match(sidebarSource, /annotation-reference-focus-button/);
  assert.doesNotMatch(sidebarSource, /className="annotation-reference-row"[\s\S]*?role="button"/);
  assert.match(sidebarSource, /annotationPlanLatestChoices/);
  assert.match(sidebarSource, /onChoice\(choice\)/);
  assert.match(sidebarSource, /onSave/);
  assert.match(sidebarSource, /onApplySmallChange/);
  assert.match(sidebarSource, /onSendToInbox/);
  assert.match(sidebarSource, /onDiscard/);
  assert.match(sidebarSource, /去收件箱/);
  assert.match(sidebarCss, /\.annotation-sidebar\s*\{[\s\S]*?position: relative;[\s\S]*?flex: 0 0 clamp\(340px, 30vw, 440px\);/);
  assert.match(sidebarCss, /\.annotation-action-ladder\s*\{[\s\S]*?grid-template-columns: repeat\(2, minmax\(0, 1fr\)\);/);
  assert.match(sidebarCss, /\.annotation-sidebar\s*\{[\s\S]*?height: 100vh;/);
  assert.match(sidebarCss, /@media \(max-width: 760px\)[\s\S]*?\.annotation-sidebar\s*\{[\s\S]*?height: min\(78vh, 620px\);/);
});
