// Generated by scripts/domain-packages.mjs. Do not edit.
import type {
  DomainMainHost,
  DomainMainSystemCapabilityInvoker,
  DomainRuntimeContributionOwner
} from '@sciforge/domain-sdk/host'
import { defineInstalledMainDomainEntrySet } from '@sciforge/domain-sdk/main'
import { createDomainMainEntry as createDomainMainEntry0 } from '@sciforge/domain-anchored-comments/main'
import { createDomainMainEntry as createDomainMainEntry1 } from '@sciforge/domain-artifact-versions/main'
import { createDomainMainEntry as createDomainMainEntry2 } from '@sciforge/domain-biology-room/main'
import { createDomainMainEntry as createDomainMainEntry3 } from '@sciforge/domain-browser-preview/main'
import { createDomainMainEntry as createDomainMainEntry4 } from '@sciforge/domain-change-inspector/main'
import { createDomainMainEntry as createDomainMainEntry5 } from '@sciforge/domain-create-loop/main'
import { createDomainMainEntry as createDomainMainEntry6 } from '@sciforge/domain-dataset-api/main'
import { createDomainMainEntry as createDomainMainEntry7 } from '@sciforge/domain-evidence-dag/main'
import { createDomainMainEntry as createDomainMainEntry8 } from '@sciforge/domain-git-checkpoints/main'
import { createDomainMainEntry as createDomainMainEntry9 } from '@sciforge/domain-life-science-preview/main'
import { createDomainMainEntry as createDomainMainEntry10 } from '@sciforge/domain-paper-radar/main'
import { createDomainMainEntry as createDomainMainEntry11 } from '@sciforge/domain-project-dag/main'
import { createDomainMainEntry as createDomainMainEntry12 } from '@sciforge/domain-remote-ssh/main'
import { createDomainMainEntry as createDomainMainEntry13 } from '@sciforge/domain-research-checkpoints/main'
import { createDomainMainEntry as createDomainMainEntry14 } from '@sciforge/domain-scientific-compute/main'
import { createDomainMainEntry as createDomainMainEntry15 } from '@sciforge/domain-scientific-plotting/main'
import { createDomainMainEntry as createDomainMainEntry16 } from '@sciforge/domain-visual-review/main'
import type { z } from 'zod'
import { installedDomainPackages } from '../../shared/installed-domain-packages'
import { defineCapability, type DefineCapabilityOptions } from '../capabilities/registry'

export type InstalledMainDomainHost = Omit<DomainMainHost, 'defineCapability' | 'capabilities'> & Readonly<{
  capabilityInvokerFor: (owner: DomainRuntimeContributionOwner) => DomainMainSystemCapabilityInvoker
}>

export function createInstalledMainDomainEntries(host: InstalledMainDomainHost) {
  const { capabilityInvokerFor, ...sharedHost } = host
  const domainHostFor = (packageName: string): DomainMainHost => {
    const definition = installedDomainPackages.definitions.find(
      (candidate) => candidate.packageName === packageName
    )
    if (!definition) throw new Error(`Installed main domain package ${packageName} is unavailable.`)
    return {
      ...sharedHost,
      capabilities: capabilityInvokerFor(Object.freeze({
        moduleId: definition.module.id,
        moduleVersion: definition.module.version
      })),
      defineCapability: (options) => defineCapability(
        options as DefineCapabilityOptions<z.ZodType, z.ZodType>
      )
    }
  }
  return defineInstalledMainDomainEntrySet<unknown>(
    installedDomainPackages,
    [
      createDomainMainEntry0(domainHostFor("@sciforge/domain-anchored-comments")),
      createDomainMainEntry1(domainHostFor("@sciforge/domain-artifact-versions")),
      createDomainMainEntry2(domainHostFor("@sciforge/domain-biology-room")),
      createDomainMainEntry3(domainHostFor("@sciforge/domain-browser-preview")),
      createDomainMainEntry4(domainHostFor("@sciforge/domain-change-inspector")),
      createDomainMainEntry5(domainHostFor("@sciforge/domain-create-loop")),
      createDomainMainEntry6(domainHostFor("@sciforge/domain-dataset-api")),
      createDomainMainEntry7(domainHostFor("@sciforge/domain-evidence-dag")),
      createDomainMainEntry8(domainHostFor("@sciforge/domain-git-checkpoints")),
      createDomainMainEntry9(domainHostFor("@sciforge/domain-life-science-preview")),
      createDomainMainEntry10(domainHostFor("@sciforge/domain-paper-radar")),
      createDomainMainEntry11(domainHostFor("@sciforge/domain-project-dag")),
      createDomainMainEntry12(domainHostFor("@sciforge/domain-remote-ssh")),
      createDomainMainEntry13(domainHostFor("@sciforge/domain-research-checkpoints")),
      createDomainMainEntry14(domainHostFor("@sciforge/domain-scientific-compute")),
      createDomainMainEntry15(domainHostFor("@sciforge/domain-scientific-plotting")),
      createDomainMainEntry16(domainHostFor("@sciforge/domain-visual-review"))
    ]
  ).entries
}
