"""Sense-agnostic Computer Use action loop."""

from .contracts import (
    ActionPlan,
    ActionTarget,
    ApprovalRequest,
    ComputerUseHostPorts,
    ComputerUseRequest,
    ComputerUseResult,
    ExecutionOutcome,
    Grounding,
    LoopStep,
    Observation,
    Verification,
)
from .loop import run_computer_use_task, run_task
from .evidence_ledger import (
    EvidenceLedger,
    build_evidence_index,
    build_evidence_snapshot,
    build_planner_brief,
)
from .isolated_desktop_contracts import EXECUTOR_COMMAND_EVENT_LOG_SCHEMA
from .isolated_desktop_l1_smoke_evidence import (
    build_isolated_desktop_l1_smoke_evidence,
    validate_isolated_desktop_l1_smoke_evidence,
)
from .isolated_desktop_l3_workflow_evidence import (
    build_isolated_desktop_l3_workflow_evidence,
    validate_isolated_desktop_l3_workflow_evidence,
)
from .repair_manifest import validate_repair_manifest
from .safety import assess_action_risk
from .trace import (
    build_repair_replay_evidence,
    build_target_bound_real_window_probe_evidence,
    build_viewport_recovery_evidence,
    compact_result,
    compact_result_for_handoff,
    result_to_trace,
    validate_repair_replay_evidence,
    validate_target_bound_real_window_probe_evidence,
    validate_trace,
    validate_viewport_recovery_evidence,
)
from .virtual_input_adapter import (
    build_target_bound_input_adapter_manifest,
    validate_input_adapter_manifest_for_real_desktop,
)
from .visible_viewer import build_visible_run_viewer, validate_visible_run_viewer_manifest
from .api import (
    buildRepairReplayEvidence,
    buildTargetBoundRealWindowProbeEvidence,
    buildTargetBoundInputAdapterManifest,
    buildVisibleRunViewer,
    buildEvidenceIndex,
    buildEvidenceSnapshot,
    buildIsolatedDesktopL1SmokeEvidence,
    buildIsolatedDesktopL3WorkflowEvidence,
    buildPlannerBrief,
    buildViewportRecoveryEvidence,
    compactResult,
    executorCommandEventLogSchema,
    getManifest,
    get_manifest,
    runTask,
    validateInputAdapterManifestForRealDesktop,
    validateIsolatedDesktopL1SmokeEvidence,
    validateIsolatedDesktopL3WorkflowEvidence,
    validateRepairManifest,
    validateRepairReplayEvidence,
    validateTargetBoundRealWindowProbeEvidence,
    validateTrace,
    validateVisibleRunViewerManifest,
    validateViewportRecoveryEvidence,
)

__all__ = [
    "ActionPlan",
    "ActionTarget",
    "ApprovalRequest",
    "ComputerUseHostPorts",
    "ComputerUseRequest",
    "ComputerUseResult",
    "ExecutionOutcome",
    "Grounding",
    "LoopStep",
    "Observation",
    "Verification",
    "EvidenceLedger",
    "EXECUTOR_COMMAND_EVENT_LOG_SCHEMA",
    "assess_action_risk",
    "build_evidence_index",
    "buildEvidenceIndex",
    "build_evidence_snapshot",
    "buildEvidenceSnapshot",
    "build_planner_brief",
    "buildPlannerBrief",
    "executorCommandEventLogSchema",
    "build_isolated_desktop_l1_smoke_evidence",
    "buildIsolatedDesktopL1SmokeEvidence",
    "build_isolated_desktop_l3_workflow_evidence",
    "buildIsolatedDesktopL3WorkflowEvidence",
    "build_repair_replay_evidence",
    "buildRepairReplayEvidence",
    "build_target_bound_real_window_probe_evidence",
    "buildTargetBoundRealWindowProbeEvidence",
    "build_target_bound_input_adapter_manifest",
    "buildTargetBoundInputAdapterManifest",
    "build_viewport_recovery_evidence",
    "buildViewportRecoveryEvidence",
    "build_visible_run_viewer",
    "buildVisibleRunViewer",
    "compact_result",
    "compactResult",
    "compact_result_for_handoff",
    "getManifest",
    "get_manifest",
    "result_to_trace",
    "run_computer_use_task",
    "run_task",
    "runTask",
    "validate_input_adapter_manifest_for_real_desktop",
    "validateInputAdapterManifestForRealDesktop",
    "validate_isolated_desktop_l1_smoke_evidence",
    "validateIsolatedDesktopL1SmokeEvidence",
    "validate_isolated_desktop_l3_workflow_evidence",
    "validateIsolatedDesktopL3WorkflowEvidence",
    "validateRepairManifest",
    "validate_repair_manifest",
    "validateRepairReplayEvidence",
    "validate_repair_replay_evidence",
    "validate_target_bound_real_window_probe_evidence",
    "validateTargetBoundRealWindowProbeEvidence",
    "validateTrace",
    "validate_trace",
    "validate_visible_run_viewer_manifest",
    "validateVisibleRunViewerManifest",
    "validateViewportRecoveryEvidence",
    "validate_viewport_recovery_evidence",
]
