"""Shared contract identifiers for isolated desktop Computer Use runs."""

from __future__ import annotations

ISOLATED_DESKTOP_BACKEND_PROBE_SCHEMA_VERSION = (
    "sciforge.computer-use.isolated-desktop-backend-probe.v1"
)
BACKEND_KIND = "linux-novnc-libreoffice-browser"
TARGET_ENVIRONMENT_KIND = "linux-isolated-desktop-session"
REMOTE_DESKTOP_INPUT_CHANNEL = "remote-desktop-isolated-session"
ISOLATED_CAPTURE_SOURCE = "isolated-virtual-display"

BACKEND_READINESS_PROOF_SCHEMA_VERSION = (
    "sciforge.computer-use.backend-readiness-proof.v2"
)
EXECUTOR_COMMAND_EVENT_LOG_SCHEMA = (
    "sciforge.computer-use.executor-command-event-log.v1"
)

ISOLATED_TARGET_WINDOW_SCHEMA_VERSION = (
    "sciforge.computer-use.isolated-target-window.v1"
)
LEGACY_L1_TARGET_WINDOW_SCHEMA_VERSION = (
    "sciforge.computer-use.l1-target-window.v1"
)
ISOLATED_TARGET_WINDOW_SCHEMAS = (
    ISOLATED_TARGET_WINDOW_SCHEMA_VERSION,
    LEGACY_L1_TARGET_WINDOW_SCHEMA_VERSION,
)

ISOLATED_RUNTIME_RESOURCE_ALLOCATION_SCHEMA_VERSION = (
    "sciforge.computer-use.isolated-runtime-resource-allocation.v1"
)
LEGACY_L1_RUNTIME_RESOURCE_ALLOCATION_SCHEMA_VERSION = (
    "sciforge.computer-use.l1-runtime-resource-allocation.v1"
)
ISOLATED_RUNTIME_RESOURCE_ALLOCATION_SCHEMAS = (
    ISOLATED_RUNTIME_RESOURCE_ALLOCATION_SCHEMA_VERSION,
    LEGACY_L1_RUNTIME_RESOURCE_ALLOCATION_SCHEMA_VERSION,
)

__all__ = [
    "BACKEND_KIND",
    "BACKEND_READINESS_PROOF_SCHEMA_VERSION",
    "EXECUTOR_COMMAND_EVENT_LOG_SCHEMA",
    "ISOLATED_CAPTURE_SOURCE",
    "ISOLATED_DESKTOP_BACKEND_PROBE_SCHEMA_VERSION",
    "ISOLATED_RUNTIME_RESOURCE_ALLOCATION_SCHEMA_VERSION",
    "ISOLATED_RUNTIME_RESOURCE_ALLOCATION_SCHEMAS",
    "ISOLATED_TARGET_WINDOW_SCHEMA_VERSION",
    "ISOLATED_TARGET_WINDOW_SCHEMAS",
    "LEGACY_L1_RUNTIME_RESOURCE_ALLOCATION_SCHEMA_VERSION",
    "LEGACY_L1_TARGET_WINDOW_SCHEMA_VERSION",
    "REMOTE_DESKTOP_INPUT_CHANNEL",
    "TARGET_ENVIRONMENT_KIND",
]
