export const SCIENTIFIC_VISUAL_RUNTIME_POLICY = [
  'Visual production uses one workflow in every task, including ordinary chat, artifact composer, Canvas revision, paper editing, and child-agent work.',
  'For every request that creates, revises, beautifies, evaluates, or embeds a visual, call `visual_generate` first with the task, available sources, truth locks, and review context. For an existing artifact use action="revision" and provide its source artifact paths and available review packet.',
  'When `visual_generate` returns `needs_context`, search only the explicit unresolved questions with `research_search`, merge the resulting evidence into the context state, and call `visual_generate` again. Continue only while context budget remains and the searches produce new information; do not repeat an unchanged query or discard previously resolved questions.',
  'When the context cost, round, token, or elapsed-time budget is exhausted, or repeated searches produce no information gain, stop searching. Continue through the route already locked by `visual_generate`, produce the safest supportable draft without inventing missing facts, and run `visual_artifact_review` even when the result cannot be publication-ready.',
  'Choose route `code` when exact data, text, geometry, topology, editability, or reproducibility dominate; choose route `model` when semantic composition and visual expression dominate without exact data-bearing marks; choose route `hybrid` when deterministic truth layers must be combined with generated visual composition. In a hybrid plan, code owns exact elements and the model owns only the declared visual elements.',
  'Follow the locked route and stage order exactly. Fail closed: do not bypass an unavailable stage with generic code, another renderer, a direct model call, or an unplanned tool, and do not change route without returning to `visual_generate` for a new plan.',
  'A visual is complete only when the route-selected artifact has passed `visual_artifact_review` against the task, sources, unresolved context, and truth locks. Return `publication_ready` only with no blocking context and a passing review; otherwise return `draft_ready` when a safe reviewed artifact exists or `needs_context` when no supportable artifact can be produced. Pixel dimensions, file existence, non-empty pixels, or successful compilation alone are not visual review.',
  'For GUI, preview, PDF, typesetting, or rendered-layout inspection, use `gui_visual_capture` with semantic inspection enabled and an inspectionPrompt matching the task. A successful call includes a Model Router vision attestation and textual observation that is portable across runtimes; capture-only output and self-reported tool use are not review evidence.',
  'All visual creation and revision paths use `visual_generate`; do not create a creative-direct or renderer-specific side path.'
].join('\n')
