import assert from 'node:assert/strict';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { runWorkspaceRuntimeGateway } from '../../src/runtime/workspace-runtime-gateway.js';

const workspace = await mkdtemp(join(tmpdir(), 'bioagent-t057-kg-'));
const prompt = [
  '构建 KRAS G12D、SHP2、EGFR、MEK、ERK、adagrasib、sotorasib 的知识图谱，',
  '要求实体归一化、关系抽取、证据引用、冲突关系、网络可视化和可复现报告。',
].join('');

const result = await runWorkspaceRuntimeGateway({
  skillDomain: 'knowledge',
  prompt,
  workspacePath: workspace,
  availableSkills: ['agentserver.generate.knowledge'],
  expectedArtifactTypes: ['research-report', 'omics-differential-expression', 'knowledge-graph'],
  selectedComponentIds: ['report-viewer', 'network-graph', 'evidence-matrix', 'execution-unit-table'],
  uiState: {
    freshTaskGeneration: true,
    forceAgentServerGeneration: true,
    expectedArtifactTypes: ['research-report', 'omics-differential-expression', 'knowledge-graph'],
    selectedComponentIds: ['report-viewer', 'network-graph', 'evidence-matrix', 'execution-unit-table'],
  },
});

assert.equal(result.executionUnits[0]?.status, 'repair-needed');
assert.notEqual(result.executionUnits[0]?.skillId, 'knowledge.uniprot_chembl_lookup');
assert.doesNotMatch(String(result.reasoningTrace), /local_kras_pathway_kg|UniProt REST with exact reviewed human gene disambiguation/);
assert.equal(
  result.artifacts.some(
    (artifact) => artifact.type === 'knowledge-graph' && asRecord(artifact.metadata).status !== 'repair-needed',
  ),
  false,
);
assert.match(
  String(result.message),
  /AgentServer|generation|configured|base URL|repair/i,
  'T057 complex KG must be generated by BioAgent/AgentServer or report a repair-needed blocker, not answered by fixed local Python code.',
);

console.log('[ok] T057 complex KG is guarded: fixed local Python does not fabricate task-specific graph answers');

function asRecord(value: unknown): Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value) ? (value as Record<string, unknown>) : {};
}
