import assert from 'node:assert/strict';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { runWorkspaceRuntimeGateway } from '../../src/runtime/workspace-runtime-gateway.js';

const workspace = await mkdtemp(join(tmpdir(), 'sciforge-agentserver-unavailable-'));
const result = await runWorkspaceRuntimeGateway({
  skillDomain: 'literature',
  prompt: 'Create a custom meta-analysis workflow that must be generated by AgentServer',
  workspacePath: workspace,
  availableSkills: ['force-agentserver-fallback'],
  scenarioPackageRef: { id: 'custom-literature-workflow', version: '0.1.0', source: 'workspace' },
  skillPlanRef: 'skill-plan/custom-literature-workflow@0.1.0',
  uiPlanRef: 'ui-plan/custom-literature-workflow@0.1.0',
});

assertRepairNeededAgentServer(result, 'custom-literature-workflow');

const cellResult = await runWorkspaceRuntimeGateway({
  skillDomain: 'omics',
  prompt: '创建 scRNA atlas 复现场景，完成 QC、整合、聚类、marker gene、细胞类型注释和跨组织组成比较',
  workspacePath: workspace,
  availableSkills: ['omics.differential_expression'],
  expectedArtifactTypes: ['omics-differential-expression', 'research-report'],
  selectedComponentIds: ['point-set-viewer', 'report-viewer', 'execution-unit-table', 'notebook-timeline'],
  scenarioPackageRef: { id: 'complex-cell-atlas', version: '0.1.0', source: 'workspace' },
  skillPlanRef: 'skill-plan/complex-cell-atlas@0.1.0',
  uiPlanRef: 'ui-plan/complex-cell-atlas@0.1.0',
});

assertRepairNeededAgentServer(cellResult, 'complex-cell-atlas');

console.log('[ok] AgentServer unavailable diagnostics include route, package refs, required inputs, and recovery actions');

function assertRepairNeededAgentServer(result: Awaited<ReturnType<typeof runWorkspaceRuntimeGateway>>, scenarioId: string) {
  assert.ok(result.artifacts.some((artifact) => artifact.type === 'runtime-diagnostic'));
  assert.ok(result.artifacts.some((artifact) => artifact.type === 'verification-result'));
  assert.equal(result.executionUnits.length, 1);

  const unit = result.executionUnits[0] as Record<string, unknown>;
  assert.equal(unit.status, 'repair-needed');
  assert.match(String(unit.failureReason || result.message), /AgentServer|base URL/i);
  assert.equal((unit.scenarioPackageRef as Record<string, unknown> | undefined)?.id, scenarioId);
  assert.equal((unit.routeDecision as Record<string, unknown> | undefined)?.selectedRuntime, 'agentserver-generation');
  assert.ok((unit.requiredInputs as string[] | undefined)?.includes('agentServerBaseUrl'));
  assert.ok((unit.recoverActions as string[] | undefined)?.some((action) => /AgentServer|网络|network/i.test(action)));
  assert.match(String(unit.nextStep), /AgentServer|network|服务恢复|local skill|重试/i);
}
