import type { UIComponentElement } from './elementTypes';

export const uiComponentElements: UIComponentElement[] = [
  {
    id: 'component.report-viewer',
    kind: 'ui-component',
    version: '1.0.0',
    label: 'Report viewer',
    description: 'Render structured markdown or sectioned research-report artifacts.',
    source: 'built-in',
    componentId: 'report-viewer',
    acceptsArtifactTypes: ['research-report'],
    requiredFields: ['markdown'],
    emptyState: {
      title: '等待 research-report',
      detail: '报告视图需要 research-report artifact，至少包含 markdown 或 sections 字段；可由 AgentServer/native backend 在运行期生成。',
    },
    recoverActions: ['run-current-scenario', 'repair-task:report-generation', 'fallback-component:unknown-artifact-inspector'],
    viewParams: ['filter', 'limit'],
    interactionEvents: ['open-ref', 'select-section'],
    roleDefaults: ['experimental-biologist', 'pi'],
    fallback: 'unknown-artifact-inspector',
  },
  {
    id: 'component.paper-card-list',
    kind: 'ui-component',
    version: '1.0.0',
    label: 'Paper cards',
    description: 'Render PubMed/Semantic Scholar style paper-list artifacts as evidence cards.',
    source: 'built-in',
    componentId: 'paper-card-list',
    acceptsArtifactTypes: ['paper-list'],
    requiredFields: ['papers'],
    emptyState: {
      title: '等待真实 paper-list',
      detail: '文献卡片需要 paper-list artifact 的 papers 字段；请运行 literature.pubmed_search 或导入包含 paper-list 的 package。',
    },
    recoverActions: ['run-skill:literature.pubmed_search', 'inspect-artifact-schema:paper-list', 'import-package:literature'],
    viewParams: ['filter', 'sort', 'limit', 'colorBy'],
    interactionEvents: ['select-paper', 'select-target'],
    roleDefaults: ['experimental-biologist', 'pi'],
    fallback: 'data-table',
  },
  {
    id: 'component.molecule-viewer',
    kind: 'ui-component',
    version: '1.0.0',
    label: 'Molecule viewer',
    description: 'Render structure-summary artifacts with 3Dmol-based structure visualization.',
    source: 'built-in',
    componentId: 'molecule-viewer',
    acceptsArtifactTypes: ['structure-summary'],
    requiredFields: ['dataRef'],
    emptyState: {
      title: '等待真实 structure-summary',
      detail: '结构查看器需要 structure-summary artifact，最好包含 dataRef 或 PDB/UniProt 字段；没有坐标时不会加载 demo 结构。',
    },
    recoverActions: ['run-skill:structure.rcsb_latest_or_entry', 'add-field:dataRef', 'inspect-artifact-schema:structure-summary'],
    viewParams: ['colorBy', 'highlightSelection', 'syncViewport'],
    interactionEvents: ['highlight-residue', 'select-chain'],
    roleDefaults: ['experimental-biologist', 'bioinformatician'],
    fallback: 'unknown-artifact-inspector',
  },
  {
    id: 'component.volcano-plot',
    kind: 'ui-component',
    version: '1.0.0',
    label: 'Volcano plot',
    description: 'Render differential-expression points as a volcano plot.',
    source: 'built-in',
    componentId: 'volcano-plot',
    acceptsArtifactTypes: ['omics-differential-expression'],
    requiredFields: ['points'],
    emptyState: {
      title: '等待真实 volcano points',
      detail: '火山图需要 omics-differential-expression artifact 的 points/logFC/pValue 数据；请先运行差异表达 skill。',
    },
    recoverActions: ['run-skill:omics.differential_expression', 'map-fields:logFC,pValue', 'fallback-component:data-table'],
    viewParams: ['colorBy', 'filter', 'x', 'y', 'label'],
    interactionEvents: ['select-gene'],
    roleDefaults: ['bioinformatician', 'pi'],
    fallback: 'data-table',
  },
  {
    id: 'component.heatmap-viewer',
    kind: 'ui-component',
    version: '1.0.0',
    label: 'Heatmap viewer',
    description: 'Render matrix payloads from omics artifacts.',
    source: 'built-in',
    componentId: 'heatmap-viewer',
    acceptsArtifactTypes: ['omics-differential-expression'],
    requiredFields: ['heatmap'],
    emptyState: {
      title: '等待真实 heatmap matrix',
      detail: '热图需要 heatmap.matrix 或 matrix 字段；当前 artifact 不满足矩阵视图输入契约。',
    },
    recoverActions: ['run-skill:omics.differential_expression', 'add-field:heatmap.matrix', 'fallback-component:data-table'],
    viewParams: ['colorBy', 'splitBy', 'facetBy'],
    interactionEvents: ['select-gene-set'],
    roleDefaults: ['bioinformatician'],
    fallback: 'data-table',
  },
  {
    id: 'component.umap-viewer',
    kind: 'ui-component',
    version: '1.0.0',
    label: 'UMAP viewer',
    description: 'Render embedding coordinates from omics artifacts.',
    source: 'built-in',
    componentId: 'umap-viewer',
    acceptsArtifactTypes: ['omics-differential-expression'],
    requiredFields: ['umap'],
    emptyState: {
      title: '等待真实 UMAP coordinates',
      detail: 'UMAP 视图需要 umap/points 中的 x/y 或 umap1/umap2 坐标；缺失时不会用 seed 图补位。',
    },
    recoverActions: ['run-skill:omics.differential_expression', 'add-field:umap', 'fallback-component:data-table'],
    viewParams: ['colorBy', 'splitBy', 'highlightSelection'],
    interactionEvents: ['select-cluster'],
    roleDefaults: ['bioinformatician', 'experimental-biologist'],
    fallback: 'data-table',
  },
  {
    id: 'component.network-graph',
    kind: 'ui-component',
    version: '1.0.0',
    label: 'Network graph',
    description: 'Render knowledge graph nodes and edges.',
    source: 'built-in',
    componentId: 'network-graph',
    acceptsArtifactTypes: ['knowledge-graph'],
    requiredFields: ['nodes', 'edges'],
    emptyState: {
      title: '等待真实 knowledge graph',
      detail: '网络图需要 knowledge-graph artifact 的 nodes/edges；请运行知识图谱 skill 或导入匹配 artifact。',
    },
    recoverActions: ['run-skill:knowledge.uniprot_chembl_lookup', 'add-fields:nodes,edges', 'fallback-component:data-table'],
    viewParams: ['colorBy', 'filter', 'highlightSelection'],
    interactionEvents: ['select-node', 'select-edge'],
    roleDefaults: ['experimental-biologist', 'pi'],
    fallback: 'data-table',
  },
  {
    id: 'component.evidence-matrix',
    kind: 'ui-component',
    version: '1.0.0',
    label: 'Evidence matrix',
    description: 'Render session claims and evidence levels.',
    source: 'built-in',
    componentId: 'evidence-matrix',
    acceptsArtifactTypes: ['paper-list', 'structure-summary', 'knowledge-graph', 'omics-differential-expression'],
    requiredFields: [],
    emptyState: {
      title: '等待 claims / evidence',
      detail: '证据矩阵需要 session claims 或可映射的 evidence 字段；运行场景后会从结果中抽取。',
    },
    recoverActions: ['run-current-scenario', 'inspect-claims', 'repair-task:evidence-extraction'],
    viewParams: ['filter', 'sort', 'limit'],
    interactionEvents: ['select-claim'],
    roleDefaults: ['experimental-biologist', 'pi', 'clinical'],
    fallback: 'unknown-artifact-inspector',
  },
  {
    id: 'component.execution-unit-table',
    kind: 'ui-component',
    version: '1.0.0',
    label: 'Execution units',
    description: 'Render reproducible execution units, logs, code refs, and statuses.',
    source: 'built-in',
    componentId: 'execution-unit-table',
    acceptsArtifactTypes: ['paper-list', 'structure-summary', 'knowledge-graph', 'omics-differential-expression', 'sequence-alignment', 'inspection-summary', 'research-report', 'runtime-artifact'],
    requiredFields: [],
    emptyState: {
      title: '等待 ExecutionUnit',
      detail: '执行单元表需要 runtime 写入 tool、params、status、hash 和输出引用；没有执行记录时保持空状态。',
    },
    recoverActions: ['rerun-current-scenario', 'inspect-runtime-route', 'export-diagnostics'],
    viewParams: ['filter', 'sort', 'limit'],
    interactionEvents: ['open-code-ref', 'open-log-ref'],
    roleDefaults: ['bioinformatician', 'pi'],
    fallback: 'unknown-artifact-inspector',
  },
  {
    id: 'component.notebook-timeline',
    kind: 'ui-component',
    version: '1.0.0',
    label: 'Notebook timeline',
    description: 'Render the structured research notebook timeline.',
    source: 'built-in',
    componentId: 'notebook-timeline',
    acceptsArtifactTypes: ['paper-list', 'structure-summary', 'knowledge-graph', 'omics-differential-expression', 'research-report', 'runtime-artifact'],
    requiredFields: [],
    emptyState: {
      title: '等待研究记录',
      detail: '研究记录来自 run、artifact、handoff 和人工决策事件；运行或导入后会自动沉淀。',
    },
    recoverActions: ['run-current-scenario', 'create-timeline-event', 'import-research-bundle'],
    viewParams: ['filter', 'sort', 'limit'],
    interactionEvents: ['select-timeline-event'],
    roleDefaults: ['experimental-biologist', 'pi'],
    fallback: 'unknown-artifact-inspector',
  },
  {
    id: 'component.data-table',
    kind: 'ui-component',
    version: '1.0.0',
    label: 'Data table',
    description: 'Generic tabular artifact renderer.',
    source: 'built-in',
    componentId: 'data-table',
    acceptsArtifactTypes: ['paper-list', 'structure-summary', 'knowledge-graph', 'omics-differential-expression', 'sequence-alignment', 'inspection-summary', 'research-report', 'runtime-artifact'],
    requiredFields: [],
    emptyState: {
      title: '等待可表格化 artifact rows',
      detail: '数据表需要 rows、papers、nodes 或其他数组字段；若 schema 不匹配，请打开 Artifact Inspector。',
    },
    recoverActions: ['inspect-artifact', 'map-array-field:rows', 'repair-ui-plan'],
    viewParams: ['filter', 'sort', 'limit', 'group'],
    interactionEvents: ['select-row'],
    roleDefaults: ['bioinformatician', 'pi'],
    fallback: 'unknown-artifact-inspector',
  },
  {
    id: 'component.unknown-artifact-inspector',
    kind: 'ui-component',
    version: '1.0.0',
    label: 'Unknown artifact inspector',
    description: 'Safe fallback for JSON, table, file, and log previews.',
    source: 'built-in',
    componentId: 'unknown-artifact-inspector',
    acceptsArtifactTypes: ['*'],
    requiredFields: [],
    emptyState: {
      title: '等待任意 runtime artifact',
      detail: '通用 inspector 会展示 JSON、表格、文件和日志引用；当前 slot 还没有可检查的 artifact。',
    },
    recoverActions: ['run-current-scenario', 'inspect-ui-manifest', 'import-matching-artifact'],
    viewParams: ['filter', 'sort', 'limit'],
    interactionEvents: ['open-ref'],
    roleDefaults: ['bioinformatician', 'pi'],
    fallback: 'unknown-artifact-inspector',
  },
];
