"""Public API exports for the SciForge Vision Sense package.

Vision Sense is sensing-only. Computer Use planning and action execution live at
the Computer Use action-provider boundary, not in this package.
"""

from .coordinates import (
    BBox,
    Point as CoordinatePoint,
    Size,
    crop_window_from_point,
    normalized_to_pixel,
    pixel_to_normalized,
    screenshot_pixel_to_system,
    system_to_screenshot_pixel,
)
from .computer_use_policy import (
    MatrixExecutionPlan,
    build_default_window_target,
    build_matrix_execution_plan,
    is_planner_only_evidence_task,
)
from .coarse_to_fine import (
    FocusRegion,
    build_focus_region,
    build_focus_region_from_trace,
    build_region_semantic_verifier,
    build_verifier_planning_feedback,
)
from .manifest import (
    DEFAULT_MANIFEST,
    DEFAULT_VISION_MODEL,
    build_default_manifest,
)
from .observer import (
    ScreenCaptureProvider,
    ScreenshotRef as ObserverScreenshotRef,
    StabilityResult,
    SupportsReadImageBytes,
    read_screenshot_bytes,
    wait_until_stable as wait_until_screen_stable,
)
from .prompts import (
    build_completion_check_prompt,
    build_crosshair_verification_prompt,
    build_screen_summary_prompt,
    build_visible_texts_prompt,
)
from .trace import (
    CaptureRect,
    MacOSScreencaptureProvider,
    ScreenshotFileMetadata,
    StaticPngScreenCaptureProvider,
    TraceScreenshotStore,
    TraceValidationResult,
    build_macos_screencapture_command,
    capture_screenshot_to_store,
    enrich_screenshot_ref,
    png_dimensions,
    validate_trace_artifact,
    validate_trace_payload,
    write_trace_artifact,
)
from .trace_contract import (
    TraceContractMetrics,
    TraceContractValidation,
    validate_computer_use_trace_contract,
    validate_computer_use_trace_contract_from_request,
)
from .types import (
    JsonMap,
    ModalityInput,
    ScreenshotRef,
    SenseManifest,
    SensePluginRequest,
    SensePluginTextEnvelope,
    SensePluginTextResult,
    build_sense_plugin_request,
)
from .upload import ScpUploadTarget, build_scp_command, scp_upload_image
from .verifier import (
    PixelChangeVerification,
    PixelDiffResult as VerifierPixelDiffResult,
    pixel_diff as verifier_pixel_diff,
    pixel_diff_ratio,
    verify_pixel_change,
)
from .visual_memory import (
    VisionMemoryBlock,
    VisionMemoryTraceInput,
    build_visual_memory_block,
    build_visual_memory_block_from_request,
)
from .vlm import (
    ParsedCompletionCheck,
    ParsedCrosshairVerification,
    ParsedVisibleText,
    VisionVlmClient,
    VisionVlmConfig,
    VisionVlmError,
    build_user_message_with_image,
    encode_image_file,
    parse_completion_check_response,
    parse_crosshair_verification_response,
    parse_visible_texts_response,
)

__all__ = [
    "BBox",
    "CaptureRect",
    "CoordinatePoint",
    "DEFAULT_MANIFEST",
    "DEFAULT_VISION_MODEL",
    "FocusRegion",
    "JsonMap",
    "MacOSScreencaptureProvider",
    "MatrixExecutionPlan",
    "ModalityInput",
    "ObserverScreenshotRef",
    "ParsedCompletionCheck",
    "ParsedCrosshairVerification",
    "ParsedVisibleText",
    "PixelChangeVerification",
    "ScreenCaptureProvider",
    "ScreenshotFileMetadata",
    "ScreenshotRef",
    "ScpUploadTarget",
    "SenseManifest",
    "SensePluginRequest",
    "SensePluginTextEnvelope",
    "SensePluginTextResult",
    "Size",
    "StabilityResult",
    "StaticPngScreenCaptureProvider",
    "SupportsReadImageBytes",
    "TraceContractMetrics",
    "TraceContractValidation",
    "TraceScreenshotStore",
    "TraceValidationResult",
    "VerifierPixelDiffResult",
    "VisionMemoryBlock",
    "VisionMemoryTraceInput",
    "VisionVlmClient",
    "VisionVlmConfig",
    "VisionVlmError",
    "build_completion_check_prompt",
    "build_crosshair_verification_prompt",
    "build_default_manifest",
    "build_default_window_target",
    "build_focus_region",
    "build_focus_region_from_trace",
    "build_macos_screencapture_command",
    "build_matrix_execution_plan",
    "build_region_semantic_verifier",
    "build_screen_summary_prompt",
    "build_scp_command",
    "build_sense_plugin_request",
    "build_user_message_with_image",
    "build_verifier_planning_feedback",
    "build_visible_texts_prompt",
    "build_visual_memory_block",
    "build_visual_memory_block_from_request",
    "capture_screenshot_to_store",
    "crop_window_from_point",
    "encode_image_file",
    "enrich_screenshot_ref",
    "is_planner_only_evidence_task",
    "normalized_to_pixel",
    "parse_completion_check_response",
    "parse_crosshair_verification_response",
    "parse_visible_texts_response",
    "pixel_diff_ratio",
    "pixel_to_normalized",
    "png_dimensions",
    "read_screenshot_bytes",
    "screenshot_pixel_to_system",
    "scp_upload_image",
    "system_to_screenshot_pixel",
    "validate_computer_use_trace_contract",
    "validate_computer_use_trace_contract_from_request",
    "validate_trace_artifact",
    "validate_trace_payload",
    "verifier_pixel_diff",
    "verify_pixel_change",
    "wait_until_screen_stable",
    "write_trace_artifact",
]
