// Generated by scripts/domain-packages.mjs. Do not edit.
import type { DomainRendererHost } from '@sciforge/domain-sdk/host'
import { defineInstalledRendererDomainEntrySet } from '@sciforge/domain-sdk/renderer'
import { createDomainRendererEntry as createDomainRendererEntry0 } from '@sciforge/domain-life-science-preview/renderer'
import { createDomainRendererEntry as createDomainRendererEntry1 } from '@sciforge/domain-paper-radar/renderer'
import { installedDomainPackages } from '@shared/installed-domain-packages'
import { rendererCapabilityClient } from '../lib/capability-client'
import { openSafeExternalUrl } from '../lib/open-external'

const domainHost: DomainRendererHost = {
  capabilityInvoker: rendererCapabilityClient,
  openExternal: async (url) => {
    await openSafeExternalUrl(url)
  }
}

export const installedRendererDomainEntrySet = defineInstalledRendererDomainEntrySet<unknown>(
  installedDomainPackages,
  [
    createDomainRendererEntry0(domainHost),
    createDomainRendererEntry1(domainHost)
  ]
)
