// Generated by scripts/domain-packages.mjs. Do not edit.
import type { DomainRendererHost } from '@sciforge/domain-sdk/host'
import { defineInstalledRendererDomainEntrySet } from '@sciforge/domain-sdk/renderer'
import { createDomainRendererEntry as createDomainRendererEntry0 } from '@sciforge/domain-browser-preview/renderer'
import { createDomainRendererEntry as createDomainRendererEntry1 } from '@sciforge/domain-evidence-dag/renderer'
import { createDomainRendererEntry as createDomainRendererEntry2 } from '@sciforge/domain-life-science-preview/renderer'
import { createDomainRendererEntry as createDomainRendererEntry3 } from '@sciforge/domain-paper-radar/renderer'
import { createDomainRendererEntry as createDomainRendererEntry4 } from '@sciforge/domain-project-dag/renderer'
import { createDomainRendererEntry as createDomainRendererEntry5 } from '@sciforge/domain-remote-ssh/renderer'
import { installedDomainPackages } from '@shared/installed-domain-packages'
import type { VisibleContextComponentSnapshot } from '@shared/visible-context'
import { rendererCapabilityClient } from '../lib/capability-client'
import { openSafeExternalUrl } from '../lib/open-external'
import {
  registerVisibleContextComponent,
  registerVisibleContextVisualTarget
} from '../lib/visible-context'
import { domainRendererNavigationHost } from './domain-renderer-navigation'

const domainHost: DomainRendererHost = {
  capabilityInvoker: rendererCapabilityClient,
  openExternal: async (url) => {
    await openSafeExternalUrl(url)
  },
  ...domainRendererNavigationHost,
  visibleContext: {
    registerComponent: (component) => registerVisibleContextComponent(
      component as VisibleContextComponentSnapshot
    ),
    registerVisualTarget: ({ element, ...input }) => registerVisibleContextVisualTarget({
      ...input,
      ...(element ? { element: element as () => Element | null } : {})
    })
  }
}

export const installedRendererDomainEntrySet = defineInstalledRendererDomainEntrySet<unknown>(
  installedDomainPackages,
  [
    createDomainRendererEntry0(domainHost),
    createDomainRendererEntry1(domainHost),
    createDomainRendererEntry2(domainHost),
    createDomainRendererEntry3(domainHost),
    createDomainRendererEntry4(domainHost),
    createDomainRendererEntry5(domainHost)
  ]
)
