import assert from 'node:assert/strict'
import test from 'node:test'

import {
  STAGE4_DEPLOYMENT,
  assertBundledStage4Contract,
  assertDomainPackageIdentity,
  auditChangedProductionSources,
  parseArchitecturePrinciplesOptions,
  safeArchiveLocator
} from './architecture-principles-gate.mjs'

test('formal gate requires the sealed Stage 4 artifact, receipt, and safe executable locator', () => {
  const options = parseArchitecturePrinciplesOptions([
    '--packed-artifact', 'dist/SciForge-0.1.0-mac-arm64.zip',
    '--artifact-receipt', 'dist/stage4-artifact-mac-arm64.json',
    '--packaged-executable-locator', 'SciForge.app/Contents/MacOS/SciForge',
    '--private-domain-package', '/private/stage4/authorization-a',
    '--private-domain-package', '/private/stage4/authorization-b'
  ])
  assert.equal(options.mode, 'formal')
  assert.equal(options.packagedExecutableLocator, 'SciForge.app/Contents/MacOS/SciForge')
  assert.deepEqual(options.privateDomainPackagePaths, [
    '/private/stage4/authorization-a',
    '/private/stage4/authorization-b'
  ])
  assert.throws(
    () => parseArchitecturePrinciplesOptions(['--packed-artifact', 'artifact.zip']),
    /--artifact-receipt is required/u
  )
  assert.throws(() => safeArchiveLocator('../SciForge.app'), /traversal/u)
  assert.throws(() => safeArchiveLocator('/Applications/SciForge.app'), /archive-relative/u)
  assert.throws(
    () => parseArchitecturePrinciplesOptions([
      '--packed-artifact', 'artifact.zip',
      '--artifact-receipt', 'stage4-artifact-mac-arm64.json',
      '--packaged-executable-locator', 'SciForge.app/Contents/MacOS/SciForge',
      '--private-domain-package', './authorization'
    ]),
    /must be absolute/u
  )
})

test('changed production audit rejects Host feature maps, private imports, and compatibility shims', () => {
  assert.deepEqual(auditChangedProductionSources([{
    path: 'packages/domains/example/src/main.ts',
    source: "import type { Secret } from '@shared/private'\n"
  }, {
    path: 'src/main/example.ts',
    source: "import '@sciforge/domain-collaboration/main'\n"
  }, {
    path: 'packages/domains/opencontent-connector/src/main/settings.ts',
    source: 'const schema = legacyConnectionSettingsSchema\n'
  }]), [
    'packages/domains/example/src/main.ts: domain package imports a Host-private source path',
    'packages/domains/opencontent-connector/src/main/settings.ts: retired production marker legacyConnectionSettingsSchema',
    'src/main/example.ts: Host contains a domain-specific import or identifier'
  ])
})

test('generated composition and package-owned domain entrypoints satisfy the static contract', () => {
  assert.deepEqual(auditChangedProductionSources([{
    path: 'src/main/modules/installed-domain-main.ts',
    source: '// Generated by scripts/domain-packages.mjs. Do not edit.\n' +
      "import '@sciforge/domain-collaboration/main'\n"
  }, {
    path: 'packages/domains/example/src/main.ts',
    source: "import type { DomainMainHost } from '@sciforge/domain-sdk/host'\n"
  }]), [])
  assert.doesNotThrow(() => assertDomainPackageIdentity({
    name: '@sciforge/domain-example',
    version: '1.2.3'
  }, {
    packageName: '@sciforge/domain-example',
    module: { version: '1.2.3' },
    entrypoints: [
      { process: 'main', export: './main' },
      { process: 'renderer', export: './renderer' }
    ]
  }, 'packages/domains/example'))
  assert.throws(() => assertDomainPackageIdentity({
    name: '@sciforge/domain-example',
    version: '1.2.3'
  }, {
    packageName: '@sciforge/domain-example',
    module: { version: '1.2.4' },
    entrypoints: [{ process: 'main', export: './main' }]
  }, 'packages/domains/example'), /versions differ/u)
})

test('packaged bundle contains frozen OIDC/build identities and no source/mock fixtures', () => {
  const sourceCommit = 'a'.repeat(40)
  const bytes = Buffer.from([
    STAGE4_DEPLOYMENT.oidcAudience,
    STAGE4_DEPLOYMENT.oidcRedirectUri,
    'sciforgeStage4Build',
    'sciforge-stage4-acceptance',
    sourceCommit,
    '@example/private-authorization',
    'packaged-production-code'
  ].join('\n'))
  assert.doesNotThrow(() => assertBundledStage4Contract(
    bytes,
    '/private/source-root',
    sourceCommit,
    {
      privateDomainPackages: [{ packageName: '@example/private-authorization' }]
    }
  ))
  assert.doesNotThrow(() => assertBundledStage4Contract(
    [
      Buffer.from([
        'sciforgeStage4Build',
        'sciforge-stage4-acceptance',
        sourceCommit,
        '@example/private-authorization'
      ].join('\n')),
      Buffer.from([
        STAGE4_DEPLOYMENT.oidcAudience,
        STAGE4_DEPLOYMENT.oidcRedirectUri,
        'packaged-production-code'
      ].join('\n'))
    ],
    '/private/source-root',
    sourceCommit,
    {
      privateDomainPackages: [{ packageName: '@example/private-authorization' }]
    }
  ))
  assert.throws(
    () => assertBundledStage4Contract(
      Buffer.from([
        STAGE4_DEPLOYMENT.oidcAudience,
        STAGE4_DEPLOYMENT.oidcRedirectUri,
        'sciforgeStage4Build',
        'sciforge-stage4-acceptance',
        sourceCommit
      ].join('\n')),
      '/private/source-root',
      sourceCommit,
      {
        privateDomainPackages: [{ packageName: '@example/private-authorization' }]
      }
    ),
    /missing private composition identity/u
  )
  assert.throws(
    () => assertBundledStage4Contract(Buffer.concat([
      bytes,
      Buffer.from('\nFakeCollaborationRepository')
    ]), '/private/source-root', sourceCommit),
    /forbidden source\/test identity/u
  )
  assert.throws(
    () => assertBundledStage4Contract(
      Buffer.from(STAGE4_DEPLOYMENT.oidcAudience),
      '/private/root',
      sourceCommit
    ),
    /missing required OIDC identity/u
  )
})
