import type { HarnessModule } from './contracts';

export const harnessModules: Record<string, HarnessModule> = {
  intent: {
    id: 'intent',
    version: '0.1.0',
    ownedStages: ['classifyIntent', 'selectProfile'],
    inputs: ['prompt', 'conversationSignals', 'runtimeConfig'],
    outputs: ['intentMode', 'explorationMode', 'riskSignals'],
    cost: 'free',
    defaultTierApplicability: ['instant', 'quick', 'bounded', 'deep', 'background'],
  },
  latency: {
    id: 'latency',
    version: '0.1.0',
    ownedStages: ['classifyIntent', 'setExplorationBudget'],
    inputs: ['prompt', 'latencyTier', 'riskSignals', 'sideEffects', 'contextAvailability'],
    outputs: ['latencyTier', 'firstResultDeadlineMs', 'backgroundAfterMs'],
    cost: 'free',
    defaultTierApplicability: ['instant', 'quick', 'bounded', 'deep', 'background'],
  },
  context: {
    id: 'context',
    version: '0.1.0',
    ownedStages: ['selectContext'],
    inputs: ['latencyTier', 'contextRefs', 'requiredContextRefs', 'blockedContextRefs'],
    outputs: ['allowedContextRefs', 'requiredContextRefs', 'contextBudget'],
    cost: 'cheap',
    defaultTierApplicability: ['instant', 'quick', 'bounded', 'deep', 'background'],
  },
  'startup-context': {
    id: 'startup-context',
    version: '0.1.0',
    ownedStages: ['onRequestReceived', 'selectContext'],
    inputs: ['workspaceRoot', 'sessionFacts', 'capabilityManifests', 'artifactRefs', 'recentRuns'],
    outputs: ['startupContextEnvelope', 'capabilityBriefIndex', 'onDemandExpansionRefs'],
    cost: 'cheap',
    defaultTierApplicability: ['instant', 'quick', 'bounded', 'deep', 'background'],
  },
  'workspace-memory': {
    id: 'workspace-memory',
    version: '0.1.0',
    ownedStages: ['selectContext', 'onAuditRecord'],
    inputs: ['artifactRefs', 'recentRuns', 'openedFiles', 'verifiedClaims', 'capabilityOutcomes'],
    outputs: ['workspaceMemoryIndex', 'reuseDecision', 'staleRefs'],
    cost: 'cheap',
    defaultTierApplicability: ['quick', 'bounded', 'deep', 'background'],
  },
  capability: {
    id: 'capability',
    version: '0.1.0',
    ownedStages: ['selectCapabilities', 'onBeforeCapabilityBroker', 'onAfterCapabilityBroker'],
    inputs: ['latencyTier', 'candidateCapabilities', 'capabilityManifests', 'failureHistory'],
    outputs: ['candidateTiers', 'escalationPlan', 'preferredCapabilityIds'],
    cost: 'cheap',
    defaultTierApplicability: ['quick', 'bounded', 'deep', 'background'],
  },
  parallel: {
    id: 'parallel',
    version: '0.1.0',
    ownedStages: ['selectCapabilities', 'onBudgetAllocate', 'onBackgroundContinuation'],
    inputs: ['candidateTasks', 'dependencyGraph', 'writeSets', 'sideEffects', 'latencyTier'],
    outputs: ['parallelWorkPlan', 'parallelTaskTrace', 'mergeDecisions'],
    cost: 'cheap',
    defaultTierApplicability: ['quick', 'bounded', 'deep', 'background'],
  },
  exploration: {
    id: 'exploration',
    version: '0.1.0',
    ownedStages: ['setExplorationBudget', 'selectCapabilities', 'onBudgetDebit'],
    inputs: ['latencyTier', 'candidateRefs', 'providerQueries', 'artifactHashes', 'verifierResults'],
    outputs: ['topKPolicy', 'earlyStopReason', 'duplicateExplorationDecision'],
    cost: 'free',
    defaultTierApplicability: ['instant', 'quick', 'bounded', 'deep', 'background'],
  },
  budget: {
    id: 'budget',
    version: '0.1.0',
    ownedStages: ['onToolPolicy', 'onBudgetAllocate', 'onBudgetDebit'],
    inputs: ['latencyTier', 'capabilityPolicy', 'budgetOverrides'],
    outputs: ['contextBudget', 'toolBudget', 'sideEffectPolicy'],
    cost: 'free',
    defaultTierApplicability: ['instant', 'quick', 'bounded', 'deep', 'background'],
  },
  verification: {
    id: 'verification',
    version: '0.1.0',
    ownedStages: ['beforeResultValidation', 'afterResultValidation', 'onVerifierVerdict'],
    inputs: ['latencyTier', 'riskSignals', 'artifactRefs', 'claims'],
    outputs: ['verificationLayers', 'selectedVerifierIds', 'validationResult'],
    cost: 'bounded',
    defaultTierApplicability: ['quick', 'bounded', 'deep', 'background'],
  },
  repair: {
    id: 'repair',
    version: '0.1.0',
    ownedStages: ['onRepairRequired', 'beforeRepairDispatch', 'afterRepairAttempt'],
    inputs: ['latencyTier', 'validationFailure', 'repairHistory', 'toolBudget'],
    outputs: ['repairContextPolicy', 'checkpointArtifacts', 'partialFailurePresentation'],
    cost: 'bounded',
    defaultTierApplicability: ['bounded', 'deep', 'background'],
  },
  progress: {
    id: 'progress',
    version: '0.1.0',
    ownedStages: ['beforeUserProgressEvent', 'onInteractionRequested', 'onBackgroundContinuation', 'onCancelRequested'],
    inputs: ['latencyTier', 'phaseState', 'elapsedMs'],
    outputs: ['progressPlan', 'partialResultDeadline', 'backgroundPolicy'],
    cost: 'free',
    defaultTierApplicability: ['instant', 'quick', 'bounded', 'deep', 'background'],
  },
  continuation: {
    id: 'continuation',
    version: '0.1.0',
    ownedStages: ['beforeResultPresentation', 'onBackgroundContinuation', 'onRunCompleted'],
    inputs: ['latencyTier', 'elapsedMs', 'firstResult', 'backgroundPolicy', 'revisionRefs'],
    outputs: ['firstResultRecord', 'backgroundContinuationRecord', 'revisionProvenance'],
    cost: 'free',
    defaultTierApplicability: ['quick', 'bounded', 'deep', 'background'],
  },
  presentation: {
    id: 'presentation',
    version: '0.1.0',
    ownedStages: ['beforeResultPresentation'],
    inputs: ['latencyTier', 'conversationPlan', 'resultPayload', 'verificationResult', 'repairResult'],
    outputs: ['conversationPlan', 'presentationPlan', 'resultPresentationContract'],
    cost: 'cheap',
    defaultTierApplicability: ['instant', 'quick', 'bounded', 'deep', 'background'],
  },
  audit: {
    id: 'audit',
    version: '0.1.0',
    ownedStages: ['onAuditRecord', 'onRunCompleted', 'onRunFailed', 'onRunCancelled'],
    inputs: ['trace', 'budgetLedger', 'repairTelemetry', 'provenance'],
    outputs: ['auditRecord', 'replayMetadata', 'trainingRecord'],
    cost: 'bounded',
    defaultTierApplicability: ['bounded', 'deep', 'background'],
  },
  research: {
    id: 'research',
    version: '0.1.0',
    ownedStages: ['beforePromptRender', 'beforeAgentDispatch'],
    inputs: ['moduleStack', 'contract', 'promptDirectives', 'promptRenderPlan'],
    outputs: ['promptDirectivePreview', 'researchEntryPoints', 'rendererBoundaryCheck'],
    cost: 'free',
    defaultTierApplicability: ['instant', 'quick', 'bounded', 'deep', 'background'],
  },
};

export function getHarnessModule(moduleId: string): HarnessModule | undefined {
  return harnessModules[moduleId];
}

export function moduleStackForTier(latencyTier: HarnessModule['defaultTierApplicability'][number]): HarnessModule[] {
  return Object.values(harnessModules).filter((module) => module.defaultTierApplicability.includes(latencyTier));
}
