"""Public API exports for the SciForge Vision Sense MVP."""

from .coordinates import (
    BBox,
    Point as CoordinatePoint,
    Size,
    crop_window_from_point,
    normalized_to_pixel,
    pixel_to_normalized,
    screenshot_pixel_to_system,
    system_to_screenshot_pixel,
)
from .computer_use import (
    ComputerUseAction,
    ComputerUseTextCommand,
    COMPUTER_USE_COMMAND_SCHEMA,
    RiskLevel,
    build_sense_plugin_request,
    command_to_text,
    computer_use_command_from_action,
    computer_use_text_envelope,
    envelope_to_text,
    text_envelope_from_vision_step,
    sense_text_result_for_computer_use,
    text_signal_from_vision_step,
)
from .executor import ExecutionResult, GuiExecutor, Point, ScrollDirection
from .kv_ground import (
    DEFAULT_REMOTE_PATH_PREFIXES,
    HealthResult,
    ImageRef,
    ImageRefKind,
    KV_GROUND_REMOTE_PATH_PREFIXES_ENV,
    KV_GROUND_URL_ENV,
    KvGroundConfig,
    KvGroundClient,
    KvGroundError,
    PredictResult,
    RemoteImageUploader,
    classify_image_ref,
    remote_path_prefixes_from_env,
)
from .manifest import (
    DEFAULT_MANIFEST,
    DEFAULT_VLM_MODEL,
    KV_GROUND_REMOTE_PATH_PREFIXES_ENV as MANIFEST_KV_GROUND_REMOTE_PATH_PREFIXES_ENV,
    KV_GROUND_URL_ENV as MANIFEST_KV_GROUND_URL_ENV,
    build_default_manifest,
)
from .observer import (
    ScreenCaptureProvider,
    ScreenshotRef as ObserverScreenshotRef,
    StabilityResult,
    SupportsReadImageBytes,
    read_screenshot_bytes,
    wait_until_stable as wait_until_screen_stable,
)
from .planner import (
    PlannerAction,
    PlannerParseError,
    PlannerValidationError,
    extract_json_object,
    parse_planner_action,
    validate_planner_action,
)
from .prompts import (
    build_completion_check_prompt,
    build_crosshair_verification_prompt,
    build_planner_prompt,
    build_screen_summary_prompt,
    build_visible_texts_prompt,
)
from .runner import (
    ActionKind,
    CompletionCheck as RunnerCompletionCheck,
    CrosshairVerification as RunnerCrosshairVerification,
    Grounder,
    GroundingResult as RunnerGroundingResult,
    Observer,
    PixelDiffResult as RunnerPixelDiffResult,
    Screenshot as RunnerScreenshot,
    TaskStatus,
    VisionAction as RunnerVisionAction,
    VisionModel,
    VisionStepRecord as RunnerVisionStepRecord,
    VisionTaskRequest as RunnerVisionTaskRequest,
    VisionTaskResult as RunnerVisionTaskResult,
    compact_vision_result_for_handoff,
    pixel_diff as runner_pixel_diff,
    run_vision_task,
    wait_until_stable as runner_wait_until_stable,
)
from .text_agent_runtime import (
    TextAgentDecision,
    TextVisionAgent,
    run_text_agent_vision_task,
)
from .trace import (
    CaptureRect,
    MacOSScreencaptureProvider,
    ScreenshotFileMetadata,
    StaticPngScreenCaptureProvider,
    TraceScreenshotStore,
    TraceValidationResult,
    build_macos_screencapture_command,
    capture_screenshot_to_store,
    enrich_screenshot_ref,
    png_dimensions,
    validate_trace_artifact,
    validate_trace_payload,
    write_trace_artifact,
)
from .upload import ScpUploadTarget, build_scp_command, scp_upload_image
from .types import (
    GroundingResult,
    JsonMap,
    ModalityInput,
    PixelDiffResult,
    ScreenshotRef,
    SenseManifest,
    SensePluginRequest,
    SensePluginTextEnvelope,
    SensePluginTextResult,
    VisionAction,
    VisionStepRecord,
    VisionTaskRequest,
    VisionTaskResult,
)
from .verifier import (
    PixelChangeVerification,
    PixelDiffResult as VerifierPixelDiffResult,
    pixel_diff as verifier_pixel_diff,
    pixel_diff_ratio,
    verify_pixel_change,
)
from .vlm import (
    ParsedCompletionCheck,
    ParsedCrosshairVerification,
    ParsedVisibleText,
    VisionVlmClient,
    VisionVlmConfig,
    VisionVlmError,
    build_user_message_with_image,
    encode_image_file,
    parse_completion_check_response,
    parse_crosshair_verification_response,
    parse_visible_texts_response,
)

__all__ = [
    "ActionKind",
    "BBox",
    "ComputerUseAction",
    "ComputerUseTextCommand",
    "COMPUTER_USE_COMMAND_SCHEMA",
    "CoordinatePoint",
    "CaptureRect",
    "DEFAULT_MANIFEST",
    "DEFAULT_REMOTE_PATH_PREFIXES",
    "DEFAULT_VLM_MODEL",
    "ExecutionResult",
    "Grounder",
    "GroundingResult",
    "GuiExecutor",
    "HealthResult",
    "ImageRef",
    "ImageRefKind",
    "JsonMap",
    "KV_GROUND_REMOTE_PATH_PREFIXES_ENV",
    "KV_GROUND_URL_ENV",
    "KvGroundConfig",
    "KvGroundClient",
    "KvGroundError",
    "MANIFEST_KV_GROUND_REMOTE_PATH_PREFIXES_ENV",
    "MANIFEST_KV_GROUND_URL_ENV",
    "MacOSScreencaptureProvider",
    "ModalityInput",
    "Observer",
    "ObserverScreenshotRef",
    "ParsedCompletionCheck",
    "ParsedCrosshairVerification",
    "ParsedVisibleText",
    "PixelChangeVerification",
    "PixelDiffResult",
    "PlannerAction",
    "PlannerParseError",
    "PlannerValidationError",
    "Point",
    "PredictResult",
    "RemoteImageUploader",
    "RiskLevel",
    "RunnerCompletionCheck",
    "RunnerCrosshairVerification",
    "RunnerGroundingResult",
    "RunnerPixelDiffResult",
    "RunnerScreenshot",
    "RunnerVisionAction",
    "RunnerVisionStepRecord",
    "RunnerVisionTaskRequest",
    "RunnerVisionTaskResult",
    "ScreenCaptureProvider",
    "ScreenshotRef",
    "ScreenshotFileMetadata",
    "ScpUploadTarget",
    "SenseManifest",
    "SensePluginRequest",
    "SensePluginTextEnvelope",
    "SensePluginTextResult",
    "Size",
    "ScrollDirection",
    "StabilityResult",
    "SupportsReadImageBytes",
    "TaskStatus",
    "TextAgentDecision",
    "TextVisionAgent",
    "TraceScreenshotStore",
    "TraceValidationResult",
    "VerifierPixelDiffResult",
    "VisionAction",
    "VisionModel",
    "VisionStepRecord",
    "VisionTaskRequest",
    "VisionTaskResult",
    "VisionVlmClient",
    "VisionVlmConfig",
    "VisionVlmError",
    "build_completion_check_prompt",
    "build_crosshair_verification_prompt",
    "build_default_manifest",
    "build_macos_screencapture_command",
    "build_scp_command",
    "build_planner_prompt",
    "build_sense_plugin_request",
    "build_screen_summary_prompt",
    "build_user_message_with_image",
    "build_visible_texts_prompt",
    "capture_screenshot_to_store",
    "classify_image_ref",
    "compact_vision_result_for_handoff",
    "command_to_text",
    "computer_use_command_from_action",
    "computer_use_text_envelope",
    "crop_window_from_point",
    "encode_image_file",
    "envelope_to_text",
    "extract_json_object",
    "normalized_to_pixel",
    "parse_completion_check_response",
    "parse_crosshair_verification_response",
    "parse_planner_action",
    "parse_visible_texts_response",
    "pixel_diff_ratio",
    "pixel_to_normalized",
    "png_dimensions",
    "read_screenshot_bytes",
    "remote_path_prefixes_from_env",
    "run_text_agent_vision_task",
    "run_vision_task",
    "runner_pixel_diff",
    "runner_wait_until_stable",
    "screenshot_pixel_to_system",
    "scp_upload_image",
    "sense_text_result_for_computer_use",
    "system_to_screenshot_pixel",
    "text_signal_from_vision_step",
    "text_envelope_from_vision_step",
    "validate_planner_action",
    "validate_trace_artifact",
    "validate_trace_payload",
    "verifier_pixel_diff",
    "verify_pixel_change",
    "wait_until_screen_stable",
    "write_trace_artifact",
]
