import assert from 'node:assert/strict'
import test from 'node:test'

import { workspaceStructuredSelectionSchema } from '../../../../src/shared/workspace-preview/index.js'
import {
  WORKSPACE_OMICS_MAX_TEXT_CHARS,
  WorkspaceOmicsService,
  createWorkspaceOmicsPreview,
  workspaceOmicsDatasetSelectionResultSchema,
  workspaceOmicsObservationSchema,
  workspaceOmicsPreviewInputSchema
} from './index.js'

test('parses Matrix Market dimensions and nnz into a bounded summary', () => {
  const service = new WorkspaceOmicsService()
  const result = service.preview({
    text: [
      '%%MatrixMarket matrix coordinate integer general',
      '% generated by test fixture',
      '3 4 5',
      '1 1 10',
      '2 3 4'
    ].join('\n'),
    path: 'counts.mtx'
  })

  assert.equal(result.format, 'matrix-market')
  assert.equal(result.matrices.length, 1)
  assert.equal(result.matrices[0]?.rowCount, 3)
  assert.equal(result.matrices[0]?.columnCount, 4)
  assert.equal(result.matrices[0]?.nonZeroCount, 5)
  assert.equal(result.matrices[0]?.storage, 'coordinate')
  assert.equal(result.matrices[0]?.field, 'integer')
  assert.equal(result.matrices[0]?.symmetry, 'general')
  assert.equal(result.metadata.source, 'matrix-market-comments')
  assert.ok(result.metadata.entries.some((entry) => entry.key === 'matrixMarket.nnz' && entry.value === '5'))
  assert.deepEqual(result.warnings, [])
})

test('extracts JSON-like H5AD metadata while keeping binary payload as a placeholder', () => {
  const result = createWorkspaceOmicsPreview(workspaceOmicsPreviewInputSchema.parse({
    text: JSON.stringify({
      n_obs: 2700,
      n_vars: 32738,
      X: {
        shape: [2700, 32738],
        nnz: 2286884
      },
      organism: 'human'
    }),
    path: 'pbmc.h5ad'
  }))

  assert.equal(result.format, 'h5ad')
  assert.ok(result.placeholder)
  assert.match(result.placeholder?.reason ?? '', /disabled/)
  assert.equal(result.metadata.source, 'json')
  assert.ok(result.metadata.entries.some((entry) => entry.key === 'n_obs' && entry.value === '2700'))
  assert.equal(result.dataset?.nObs, 2700)
  assert.equal(result.dataset?.nVars, 32738)
  assert.deepEqual(result.dataset?.shape, [2700, 32738])
  assert.equal(result.dataset?.nnz, 2286884)
  assert.equal(result.matrices[0]?.source, 'metadata')
  assert.deepEqual(result.matrices[0]?.shape, [2700, 32738])
  assert.equal(result.matrices[0]?.rowCount, 2700)
  assert.equal(result.matrices[0]?.columnCount, 32738)
  assert.equal(result.matrices[0]?.nonZeroCount, 2286884)
})

test('extracts nested Zarr axis metadata and embedding names while keeping payloads placeholder-only', () => {
  const service = new WorkspaceOmicsService()
  const result = service.preview({
    text: JSON.stringify({
      attrs: {
        n_obs: 100,
        n_vars: 200
      },
      X: {
        shape: [100, 200],
        nnz: 1234
      },
      obs: {
        cell_type: { categories: ['T cell', 'B cell'] },
        batch: { dtype: 'category' }
      },
      var: {
        gene_symbol: { dtype: 'string' },
        highly_variable: { dtype: 'bool' }
      },
      obsm: {
        X_umap: { shape: [100, 2] },
        X_pca: { shape: [100, 50] }
      }
    }),
    path: 'atlas.zarr'
  })

  assert.equal(result.format, 'zarr')
  assert.ok(result.placeholder)
  assert.equal(result.dataset?.nObs, 100)
  assert.equal(result.dataset?.nVars, 200)
  assert.deepEqual(result.dataset?.shape, [100, 200])
  assert.equal(result.dataset?.nnz, 1234)
  assert.equal(result.dataset?.obsKeyCount, 2)
  assert.equal(result.dataset?.varKeyCount, 2)
  assert.deepEqual(result.dataset?.obsKeys, ['cell_type', 'batch'])
  assert.deepEqual(result.dataset?.varKeys, ['gene_symbol', 'highly_variable'])
  assert.deepEqual(result.dataset?.embeddingNames, ['X_umap', 'X_pca'])
  assert.deepEqual(result.matrices[0]?.shape, [100, 200])
  assert.match(result.observation?.visibleText ?? '', /Embeddings: X_umap, X_pca/)
  assert.deepEqual(result.observation?.omics.dataset?.embeddingNames, ['X_umap', 'X_pca'])
})

test('selects obs keys, var keys, and embeddings from H5AD-like metadata summaries', () => {
  const service = new WorkspaceOmicsService()
  const preview = service.preview({
    text: JSON.stringify({
      n_obs: 50,
      n_vars: 10,
      X: { shape: [50, 10] },
      obs: {
        cell_type: { dtype: 'category' },
        batch: { dtype: 'category' }
      },
      var: {
        gene_symbol: { dtype: 'string' },
        highly_variable: { dtype: 'bool' }
      },
      obsm: {
        X_umap: { shape: [50, 2] },
        X_pca: { shape: [50, 5] }
      }
    }),
    path: 'pbmc.h5ad'
  })

  const selection = service.selectDataset({
    preview,
    obsKeys: ['cell_type', 'batch'],
    varKeys: ['gene_symbol'],
    embeddingNames: ['X_umap']
  })

  workspaceOmicsDatasetSelectionResultSchema.parse(selection)
  workspaceStructuredSelectionSchema.parse(selection.selection)
  assert.equal(selection.selection.kind, 'omics')
  assert.deepEqual(selection.selection.obsKeys, ['cell_type', 'batch'])
  assert.deepEqual(selection.selection.varKeys, ['gene_symbol'])
  assert.deepEqual(selection.selection.embeddings, ['X_umap'])
  assert.deepEqual(selection.missing.obsKeys, [])
  assert.deepEqual(selection.warnings, [])
  assert.match(selection.visibleText ?? '', /Obs keys: cell_type, batch/)
})

test('selects Matrix Market matrices and metadata-backed axis ranges', () => {
  const service = new WorkspaceOmicsService()
  const preview = service.preview({
    text: '%%MatrixMarket matrix coordinate real general\n3 4 5\n',
    path: 'counts.mtx'
  })

  const selection = service.selectDataset({
    preview,
    matrixNames: ['Matrix Market matrix'],
    ranges: [
      { matrixName: 'Matrix Market matrix', axis: 'row', start: 0, end: 2 },
      { matrixId: 'matrix-1', axis: 'column', start: 1, end: 4 }
    ]
  })

  assert.deepEqual(selection.selection.matrixIds, ['matrix-1'])
  workspaceStructuredSelectionSchema.parse(selection.selection)
  assert.deepEqual(selection.selection.ranges, [
    {
      matrixId: 'matrix-1',
      matrixName: 'Matrix Market matrix',
      axis: 'row',
      start: 0,
      end: 2,
      axisLength: 3
    },
    {
      matrixId: 'matrix-1',
      matrixName: 'Matrix Market matrix',
      axis: 'column',
      start: 1,
      end: 4,
      axisLength: 4
    }
  ])
  assert.deepEqual(selection.warnings, [])
  assert.match(selection.visibleText ?? '', /Axis ranges:/)
})

test('reports missing omics selection requests with visible warnings', () => {
  const service = new WorkspaceOmicsService()
  const preview = service.preview({
    text: JSON.stringify({
      n_obs: 5,
      n_vars: 3,
      obs: { cell_type: {} },
      var: { gene_symbol: {} },
      obsm: { X_umap: { shape: [5, 2] } }
    }),
    path: 'small.h5ad'
  })

  const selection = service.selectDataset({
    preview,
    matrixIds: ['missing-matrix'],
    obsKeys: ['cell_type', 'donor'],
    varKeys: ['gene_symbol', 'ensembl_id'],
    embeddingNames: ['X_umap', 'X_tsne']
  })

  assert.deepEqual(selection.selection.obsKeys, ['cell_type'])
  assert.deepEqual(selection.selection.varKeys, ['gene_symbol'])
  assert.deepEqual(selection.selection.embeddings, ['X_umap'])
  assert.deepEqual(selection.missing.matrixIds, ['missing-matrix'])
  assert.deepEqual(selection.missing.obsKeys, ['donor'])
  assert.deepEqual(selection.missing.varKeys, ['ensembl_id'])
  assert.deepEqual(selection.missing.embeddings, ['X_tsne'])
  assert.match(selection.warnings.join('\n'), /Missing obs keys: donor/)
  assert.match(selection.visibleText ?? '', /Missing requests:/)
})

test('extracts HDF5 key-value metadata without parsing binary matrix payloads', () => {
  const result = createWorkspaceOmicsPreview(workspaceOmicsPreviewInputSchema.parse({
    text: [
      'n_obs: 42',
      'n_vars: 7',
      'shape: [42, 7]',
      'nnz: 84',
      'obs_keys: sample, condition',
      'var_keys: gene_id, symbol',
      'obsm: X_umap/X_pca'
    ].join('\n'),
    path: 'experiment.h5'
  }))

  assert.equal(result.format, 'hdf5')
  assert.ok(result.placeholder)
  assert.equal(result.metadata.source, 'key-value')
  assert.equal(result.dataset?.nObs, 42)
  assert.equal(result.dataset?.nVars, 7)
  assert.deepEqual(result.dataset?.shape, [42, 7])
  assert.equal(result.dataset?.nnz, 84)
  assert.equal(result.dataset?.obsKeyCount, 2)
  assert.equal(result.dataset?.varKeyCount, 2)
  assert.deepEqual(result.dataset?.embeddingNames, ['X_umap', 'X_pca'])
  assert.equal(result.matrices[0]?.nonZeroCount, 84)
})

test('declares safe placeholder support for generic HDF5 without parsing payloads', () => {
  const service = new WorkspaceOmicsService()
  const result = service.preview({
    path: 'assay.h5',
    size: 1024
  })

  assert.equal(result.format, 'hdf5')
  assert.ok(result.placeholder)
  assert.equal(result.matrices.length, 0)
  assert.equal(result.metadata.source, 'none')
  assert.ok(result.capabilities.some((capability) => capability.format === 'hdf5' && capability.binaryPlaceholderOnly))
  assert.match(result.warnings.join('\n'), /payload parsing is not enabled/)
})

test('emits a WorkspaceObservation-shaped omics summary', () => {
  const service = new WorkspaceOmicsService()
  const result = service.preview({
    text: '%%MatrixMarket matrix coordinate real general\n2 3 4\n',
    path: 'matrix/counts.mtx',
    workspaceRoot: '/workspace/project',
    mimeType: 'text/plain'
  })

  assert.ok(result.observation)
  const observation = workspaceOmicsObservationSchema.parse(result.observation)
  assert.equal(observation.schemaVersion, 1)
  assert.equal(observation.file.path, 'matrix/counts.mtx')
  assert.equal(observation.view.pluginId, 'omics')
  assert.equal(observation.view.modality, 'omics')
  assert.equal(observation.omics.format, 'matrix-market')
  assert.equal(observation.omics.matrices[0]?.rowCount, 2)
  assert.equal(observation.omics.matrices[0]?.columnCount, 3)
  assert.deepEqual(observation.omics.matrices[0]?.shape, [2, 3])
  assert.match(observation.visibleText ?? '', /2 x 3/)
})

test('validates preview inputs with zod contracts', () => {
  const service = new WorkspaceOmicsService()

  assert.throws(() => {
    service.preview({
      text: 'x'.repeat(WORKSPACE_OMICS_MAX_TEXT_CHARS + 1)
    })
  }, { name: 'ZodError' })
})
